### PR TITLE
Adds support for we_universal style

### PR DESCRIPTION
**Pull request by Galixte**
Hi @marc1706,

to fix the displaying because all elements in blocks are displayed on left or right side.

Source: http://forums.phpbb-fr.com/extensions-support-independantes-phpbb31/sujet205884.html#p1609679.

### CODE REVIEW

**Comment by Galixte** [comment]
Now you ca

**Comment by Galixte** [comment]
Hi @Wignatz, it"s OK for you ?

**Comment by Wignatz** [comment]
Hi @Galixte , sorry for the late answer.
I've tested on my smartphone and it works fine. Good job ;)!

Thank you!

**Comment by Galixte** [comment]
Thanks, @marc1706  could you merge this please ?

**Comment by marc1706** [comment]
Thank you very much for you contribution. Since we will have to support this style once we merge this into Board3 Portal and this will very much increase the amount we have to support, we will however have to decline this pull request.
I'd very much like to see this as a download offer in the phpbb.com support section or at www.board3.de.

**Pull request closed without merging**
